repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.14.2
    hooks:
      - id: helm-docs
        args:
          - --sort-values-order=file
          - --template-files=./_helm-docs-templates.gotmpl
          - --template-files=README.md.gotmpl
