apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.frontendFullname" . }}
  labels:
    {{- include "backstage.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "backstage.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "backstage.frontendSelectorLabels" . | nindent 8 }}
      {{- with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.frontend.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "backstage.frontendServiceAccountName" . }}
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: backstage
          {{- with .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "backstage.frontendImage" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            {{- if .Values.appConfig.app.title }}
            - name: APP_CONFIG_app_title
              value: {{ .Values.appConfig.app.title | quote }}
            {{- end }}
            {{- if .Values.appConfig.app.baseUrl }}
            - name: APP_CONFIG_app_baseUrl
              value: http://localhost:8080
            {{- end }}
            {{- if .Values.appConfig.backend.baseUrl }}
            - name: APP_CONFIG_backend_baseUrl
              value: {{ .Values.appConfig.backend.baseUrl | quote }}
            {{- end }}
            {{- if .Values.appConfig.organization.name }}
            - name: APP_CONFIG_organization_name
              value: {{ .Values.appConfig.organization.name | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
