{{- if and .Values.frontend.autoscaling.enabled (or .Values.frontend.autoscaling.targetCPUUtilizationPercentage .Values.frontend.autoscaling.targetMemoryUtilizationPercentage) }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "backstage.frontendFullname" . }}
  labels:
    {{- include "backstage.frontendLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "backstage.frontendFullname" . }}
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.frontend.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ . }}
  {{- end }}
{{- end }}
