name: Updatecli

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup updatecli
        uses: updatecli/updatecli-action@v2

      - name: Generate GitHub app token
        id: github-app-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_UPDATECLI_APP_ID }}
          private_key: ${{ secrets.GH_UPDATECLI_APP_PEM_FILE }}

      - name: Run Updatecli
        run: updatecli apply
        env:
          GITHUB_USERNAME: mcwarman-updatecli[bot]
          GITHUB_EMAIL: 141340520+mcwarman-updatecli[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ steps.github-app-token.outputs.token }}
