name: GitHub Workflow Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/workflow-test.yaml"

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Set up helm unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Run chart-testing (lint)
        run: ct lint --all --config ct.yaml

      - name: Run helm unittest
        run: echo charts/*/ | xargs -L 1 helm unittest --strict

      - name: Create Kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        run: ct install --all --config ct.yaml
